apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: frontend
  name: email-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email-con
        image: python:3.7-slim
        #command: ['sh', '-c', 'echo The app is running! && sleep 3600']        
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  selector:
    app: email
  ports:
  - port: 5000
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: email-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
   
