---
steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcr.io/formationgcp-baptiste/github.com/jamykun/email:$SHORT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/gcr.io/formationgcp-baptiste/github.com/jamykun/email:$SHORT_SHA']
# Deploy de notre image
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args: ['apply', '-f', './manifest/8-email.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
  - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-pfr-main' 
